### ISSUE TITLE
[tempo-distributed] Add OTel gRPC endpoints to nginx gateway

### ISSUE THREAD

**Issue by AlexDHoffer** [grafana/helm-charts#1389]
I'd like to hit the OTLP gRPC endpoints the distributor has. Looks to me like the chart only presently supports the http endpoints.

**Comment by agermain** [comment]
+1. Sounds like a duplicate of #733.

**Comment by ahaw023** [comment]
@AlexDHoffer 

It is a little daft

I am using an OpenTelemetry collector and this is the config I set up to make it work

```
    exporters:
       otlphttp/grafana-hosted:
        endpoint: http://tempo-distributed-gateway.grafana-tempo.svc.cluster.local:80/otlp
```

**Comment by ahaw023** [comment]
longer term fix will be to add a listener for grpc and proxy back to the config

**Comment by AlexDHoffer** [comment]
I don't know about others but I would be perfectly satisfied with circumventing the gateway pods entirely and simply adding an ingress resource that supports grpc traffic that routes to the distributor. I guess the question with this issue is how would you like to see distributor grpc endpoints exposed.

**Comment by artyom-p** [comment]
Also struggling with the same issue atm, tried to implement a workaround, the same as mentioned above - otlphttp exporter, but for some reason otlphttp cant send http headers for me, maybe im doing something wrong...

**Comment by artyom-p** [comment]
Ah, heres why its not working... https://github.com/grafana/tempo/issues/495

**Comment by sambacha** [comment]
This has been fixed in https://github.com/grafana/tempo/issues/495

**Comment by jammerful** [comment]
The OTLP gRPC port still doesn't get added to the gateway if you enable it.

**Comment by tanvir-highlevel** [comment]
> The OTLP gRPC port still doesn't get added to the gateway if you enable it.

Does anyone have a solution for this? How do we enable this?

**Comment by manueljishi** [comment]
I'm experiencing the same issue. Tempo gateway on the distributed tempo chart does not expose an endpoint for grpc (or I wasn't able to configure it) so I could not send metrics with grafana alloy (using grafana/k8s-monitoring chart). What I ended up doing was setting the tempo.protocol field to "otlphttp" on the k8s-monitoring chart so the remote write uses http instead of grpc

**Comment by Sheikh-Abubaker** [comment]
Closing as completed by https://github.com/grafana/helm-charts/pull/3678
