### ISSUE TITLE
[tempo-distributed] gateway ingress - nil pointer while executing executing "tempo.resourceName"

### ISSUE THREAD

**Issue by cbonami** [grafana/helm-charts#1934]
Using distributed-tempo chart (targetRevision: 0.27.1). 

Installation of chart fails:

Error: template: tempo-distributed/templates/gateway/ingress-gateway.yaml:45:25: executing "tempo-distributed/templates/gateway/ingress-gateway.yaml" at <include "tempo.resourceName" (dict "ctx" . "component" "gateway")>: error calling include: template: tempo-distributed/templates/_helpers.tpl:153:3: executing "tempo.resourceName" at <include "tempo.fullname" .ctx>: error calling include: template: tempo-distributed/templates/_helpers.tpl:15:14: executing "tempo.fullname" at <.Values.fullnameOverride>: nil pointer evaluating interface {}.fullnameOverride Use --debug flag to render out invalid YAML

My (only) values:

```
        gateway:
          enabled: true
          ingress:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: nginx
              cert-manager.io/cluster-issuer: cert-manager
              kubernetes.io/tls-acme: "true"
              nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
            hosts:
              - host: gateway.tempo.tools.acerta.io
                paths:
                  - path: /   
            tls:
              - hosts:
                  - gateway.tempo.tools.acerta.io
                secretName: tempo-tls

```

Downgraded to 0.26.7 -- problem disappears.

**Comment by zanhsieh** [comment]
@zalegrala 
Could you take a look please?
https://github.com/grafana/helm-charts/commit/b6994421cb0f3d100e92aad9592ad582f0930f32

**Comment by zalegrala** [comment]
Thanks for the report.  I'll take a look this week.

**Comment by zalegrala** [comment]
I believe https://github.com/grafana/helm-charts/pull/1960 will resolve the issue, but I wasn't able to reproduce this locally.  Are you able to test the change in that PR?

**Comment by zanhsieh** [comment]
@cbonami 
Could you test @zalegrala 's change please?

**Comment by Joibel** [comment]
This fix has broken things for me. 0.27.5 is fine, but 0.27.6 breaks with this minimal values.yaml

**Comment by zalegrala** [comment]
Apologies for the bad merge.  We need some CI to catch this.

Thanks for the values, I was able to reproduce locally using those, but not the original ones on this issue.

I'm not clear why this works, but it seems to, given the minimal values above.  If that fixes it, does anyone know why? https://github.com/grafana/helm-charts/pull/1964

**Comment by daper** [comment]
This issue went out of my radar and I opened a PR for the same thing straight away. I explain the why [here](https://github.com/grafana/helm-charts/pull/1967#issue-1445716493).

> It is caused by a missing context due to the `range` in [ingress-gateway.yaml:37](https://github.com/grafana/helm-charts/blob/main/charts/tempo-distributed/templates/gateway/ingress-gateway.yaml#L37). I've followed the same pattern seen on other templates here and defined a `$dict` on top which is then passed as context.

**Comment by allanhung** [comment]
I believe [#1931](https://github.com/grafana/helm-charts/pull/1931) should fix this issue.  @daper  Could you try version 0.27.2 to see if it works?

**Comment by daper** [comment]
Yes, it made it. Version `v0.27.7` deployed successfully.

**Comment by rlex** [comment]
still fails for me...
```
COMBINED OUTPUT:
  Error: Failed to render chart: exit status 1: coalesce.go:223: warning: destination for tempo-distributed.gateway.ingress.tls is a table. Ignoring non-table value ([map[hosts:[gateway.tempo.example.com] secretName:tempo-gateway-tls]])
  coalesce.go:223: warning: destination for tempo-distributed.gateway.ingress.tls is a table. Ignoring non-table value ([map[hosts:[gateway.tempo.example.com] secretName:tempo-gateway-tls]])
  Error: template: tempo-distributed/templates/gateway/secret-gateway.yaml:6:11: executing "tempo-distributed/templates/gateway/secret-gateway.yaml" at <include "tempo.resourceName" (dict "ctx" . "component" "gateway")>: error calling include: template: tempo-distributed/templates/_helpers.tpl:153:3: executing "tempo.resourceName" at <include "tempo.fullname" .ctx>: error calling include: template: tempo-distributed/templates/_helpers.tpl:15:14: executing "tempo.fullname" at <.Values.fullnameOverride>: nil pointer evaluating interface {}.fullnameOverride
  Use --debug flag to render out invalid YAML
  Error: plugin "diff" exited with error
```

i have fullnameOverride: tempo set, maybe that's reason.

**Comment by rlex** [comment]
There is two errors but first one is actually warning, so i think it's that one: 
```
  Error: Failed to render chart: exit status 1: Error: template: tempo-distributed/templates/gateway/secret-gateway.yaml:6:11: executing "tempo-distributed/templates/gateway/secret-gateway.yaml" at <include "tempo.resourceName" (dict "ctx" . "component" "gateway")>: error calling include: template: tempo-distributed/templates/_helpers.tpl:153:3: executing "tempo.resourceName" at <include "tempo.fullname" .ctx>: error calling include: template: tempo-distributed/templates/_helpers.tpl:15:14: executing "tempo.fullname" at <.Values.fullnameOverride>: nil pointer evaluating interface {}.fullnameOverride
```

I tried with both standard tls settings:
```
            tls:
              - secretName: tempo-gateway-tls
                hosts:
                  - gateway.tempo.example.com
  ```

and empty (my previous setting):
```
tls: {}
```

Returns same error to me.

version: 0.27.7

**Comment by rlex** [comment]
Looks like same issue, different file? 
Should be "$" instead of "." ? https://github.com/grafana/helm-charts/blob/main/charts/tempo-distributed/templates/gateway/secret-gateway.yaml#L6

**Comment by daper** [comment]
Ah! True, it's the same error but on different file. And with basicAuth enabled for the gw.

```sh
$ helm template tempo grafana/tempo-distributed \
  --set gateway.enabled=true \
  --set gateway.ingress.enabled=true \
  --set fullnameOverride=tempo \
  --set gateway.basicAuth.enabled=true \
  --version 0.27.7 >/dev/null
Error: template: tempo-distributed/templates/gateway/secret-gateway.yaml:6:11: executing "tempo-distributed/templates/gateway/secret-gateway.yaml" at <include "tempo.resourceName" (dict "ctx" . "component" "gateway")>: error calling include: template: tempo-distributed/templates/_helpers.tpl:153:3: executing "tempo.resourceName" at <include "tempo.fullname" .ctx>: error calling include: template: tempo-distributed/templates/_helpers.tpl:15:14: executing "tempo.fullname" at <.Values.fullnameOverride>: nil pointer evaluating interface {}.fullnameOverride

Use --debug flag to render out invalid YAML
```

**Comment by daper** [comment]
@rlex I've made a PR with the necessary changes. It worked for the template command that I've written above but could you also check that also fixes your case?

**Comment by zalegrala** [comment]
Nice, thanks @daper
