### ISSUE TITLE
[tempo] Service Monitor contains a non existent port

### ISSUE THREAD

**Issue by Mahagon** [grafana/helm-charts#3762]
Chart Version: tempo-1.23.0
K8s Version: 1.32.4

When the ServiceMonitor for the tempo chart is enabled, it contains a non existing service port "jaeger-metrics", which causes scraping errors:

https://github.com/grafana/helm-charts/blame/main/charts/tempo/templates/servicemonitor.yaml#L33

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    meta.helm.sh/release-name: grafana-tempo
    meta.helm.sh/release-namespace: tempo
  creationTimestamp: "2024-08-15T14:25:42Z"
  generation: 14
  labels:
    app: tempo
    app.kubernetes.io/managed-by: Helm
    chart: tempo-1.23.0
    heritage: Helm
  name: grafana-tempo
  namespace: tempo
  resourceVersion: "211998952"
  uid: 0b6662b3-095b-4a8a-a6e5-e41641412b70
spec:
  endpoints:
  - port: tempo-prom-metrics
  - port: jaeger-metrics
  namespaceSelector:
    matchNames:
    - tempo
  selector:
    matchLabels:
      app.kubernetes.io/instance: grafana-tempo
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: tempo
      app.kubernetes.io/version: 2.8.0
      helm.sh/chart: tempo-1.23.0
```

```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: grafana-tempo
    meta.helm.sh/release-namespace: tempo
  creationTimestamp: "2024-08-15T14:25:42Z"
  labels:
    app.kubernetes.io/instance: grafana-tempo
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: tempo
    app.kubernetes.io/version: 2.8.0
    helm.sh/chart: tempo-1.23.0
  name: grafana-tempo
  namespace: tempo
  resourceVersion: "211998943"
  uid: c54a4a90-55d4-42e3-a612-3b40180a4a9e
spec:
  clusterIP: 10.143.32.160
  clusterIPs:
  - 10.143.32.160
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: tempo-jaeger-thrift-compact
    port: 6831
    protocol: UDP
    targetPort: 6831
  - name: tempo-jaeger-thrift-binary
    port: 6832
    protocol: UDP
    targetPort: 6832
  - name: tempo-prom-metrics
    port: 3100
    protocol: TCP
    targetPort: 3100
  - name: tempo-jaeger-thrift-http
    port: 14268
    protocol: TCP
    targetPort: 14268
  - name: grpc-tempo-jaeger
    port: 14250
    protocol: TCP
    targetPort: 14250
  - name: tempo-zipkin
    port: 9411
    protocol: TCP
    targetPort: 9411
  - name: tempo-otlp-legacy
    port: 55680
    protocol: TCP
    targetPort: 55680
  - name: tempo-otlp-http-legacy
    port: 55681
    protocol: TCP
    targetPort: 55681
  - name: grpc-tempo-otlp
    port: 4317
    protocol: TCP
    targetPort: 4317
  - name: tempo-otlp-http
    port: 4318
    protocol: TCP
    targetPort: 4318
  - name: tempo-opencensus
    port: 55678
    protocol: TCP
    targetPort: 55678
  selector:
    app.kubernetes.io/instance: grafana-tempo
    app.kubernetes.io/name: tempo
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

Is there a setting i am missing? or is it a bug?
Thanks for your help in advance.

**Comment by KyriosGN0** [comment]
@Mahagon can you upgrade to 1.23.1?
 i have fixed that issue in that version

**Comment by Mahagon** [comment]
Hi,

upgrading to chart version 1.23.1 didn't fix the issue for me

the port jaeger-metrics defined in the service monitor is still not available on the endpoint or service.
Just the tempo-prom-metrics changed from 3100 to 3200, but that one wasn't an issue in the first place for me :)

I think jaeger-metrics is a port that should be dropped from the service monitor, or i am missing something

**Comment by KyriosGN0** [comment]
@Mahagon i think i know the issue, just to confirm, you don't use the tempoQuery component right?

**Comment by adinhodovic** [comment]
https://github.com/grafana/helm-charts/pull/3768

The selector labels are wrong. Fixed above.

**Comment by Mahagon** [comment]
> [@Mahagon](https://github.com/Mahagon) i think i know the issue, just to confirm, you don't use the tempoQuery component right?

right, i don't have `tempoQuery` enabled.



> [#3768](https://github.com/grafana/helm-charts/pull/3768)
> 
> The selector labels are wrong. Fixed above.

Guess this would work for me, but if `tempoQuery` enables the jaeger-metrics port, there probably should be an `if tempoQuery is enabled` around it?

**Comment by adinhodovic** [comment]
> > [@Mahagon](https://github.com/Mahagon) i think i know the issue, just to confirm, you don't use the tempoQuery component right?
> 
> right, i don't have `tempoQuery` enabled.
> 
> > [#3768](https://github.com/grafana/helm-charts/pull/3768)
> > The selector labels are wrong. Fixed above.
> 
> Guess this would work for me, but if `tempoQuery` enables the jaeger-metrics port, there probably should be an `if tempoQuery is enabled` around it?

Oh, added an if statement, wasn't aware that jaeger-metrics was a thing or tempoquery.

**Comment by Mahagon** [comment]
Tested your branch, Servicemonitor works for me now without scrape errors 

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    meta.helm.sh/release-name: grafana-tempo
    meta.helm.sh/release-namespace: tempo
  creationTimestamp: "2025-06-25T06:41:49Z"
  generation: 1
  labels:
    app: tempo
    app.kubernetes.io/managed-by: Helm
    chart: tempo-1.23.1
    heritage: Helm
  name: grafana-tempo
  namespace: tempo
  resourceVersion: "219925240"
  uid: ad013fe0-4cd3-4fd6-b146-30e1620766dc
spec:
  endpoints:
  - port: tempo-prom-metrics
  namespaceSelector:
    matchNames:
    - tempo
  selector:
    matchLabels:
      app.kubernetes.io/instance: grafana-tempo
      app.kubernetes.io/name: tempo
```
